apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # echo -n "my-secret-api-key" | base64
  API_KEY: bXktc2VjcmV0LWFwaS1rZXk=
  # echo -n "super-secret-password" | base64  
  DB_PASSWORD: c3VwZXItc2VjcmV0LXBhc3N3b3Jk
