apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: service-a
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: service-b
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: service-c
spec:
  selector:
    app: service-c
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: service-d
spec:
  selector:
    app: service-d
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
# External access service
apiVersion: v1
kind: Service
metadata:
  name: external-access
spec:
  selector:
    app: service-a
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080
  type: NodePort
