apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    app: apache-server
spec:
  type: NodePort
  selector:
    app: apache-server
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30085  # Changed from 30080 to 30085
---
# Alternative LoadBalancer service (if supported)
apiVersion: v1
kind: Service
metadata:
  name: apache-loadbalancer
  labels:
    app: apache-server
spec:
  type: LoadBalancer
  selector:
    app: apache-server
  ports:
  - name: http
    port: 80
    targetPort: 80
---
# ClusterIP service for internal access
apiVersion: v1
kind: Service
metadata:
  name: apache-clusterip
  labels:
    app: apache-server
spec:
  type: ClusterIP
  selector:
    app: apache-server
  ports:
  - name: http
    port: 80
    targetPort: 80
